"""AlphaZero-style refinement loop with safeguards against collapse.

Naive self-play from a good supervised net tends to *degrade* it: the net
overfits its own noisy, exploration-heavy games and forgets what Stockfish
taught it (catastrophic forgetting). This loop adds the guardrails that make
self-play actually help:

1. Champion/candidate split + arena gating -- a freshly trained candidate is
   only promoted to champion if it *beats* the current champion head-to-head by
   a margin. Otherwise it is reverted. The deployed net can therefore never get
   worse than where it started.
2. Supervised anchoring -- every training batch mixes a fraction of ground-truth
   Stockfish-labeled positions in with the self-play samples, so the net keeps
   its supervised knowledge instead of drifting away from it.
3. A conservative learning rate and self-play games generated by the *champion*
   (not the possibly-degraded candidate), so training data stays high quality.
4. Optional Stockfish value blending into self-play value targets.

Self-play game generation is parallelized across worker processes (see the
``_sp_*`` helpers); the champion's weights are broadcast to the workers and only
reloaded when the champion is promoted.
"""
from __future__ import annotations

import multiprocessing as mp
import os

# Must run before numpy/torch import — each worker is a separate process and
# OpenBLAS defaults to 64 threads, which exhausts pthread limits with many workers.
for _thread_var in (
    "OPENBLAS_NUM_THREADS",
    "OMP_NUM_THREADS",
    "MKL_NUM_THREADS",
    "VECLIB_MAXIMUM_THREADS",
    "NUMEXPR_NUM_THREADS",
):
    os.environ[_thread_var] = "1"

import random
from typing import List, Optional, Tuple

import chess
import numpy as np
import torch
import torch.nn.functional as F

from data.dataset import ReplayBuffer, StockfishDataset
from engine.config import Config, ModelConfig
from engine.books import (
    build_mixed_opening_pool,
    try_load_opening_book,
    try_load_tablebase,
    tablebase_forced_white_result,
)
from engine.model import build_model, load_checkpoint, save_checkpoint
from engine.player import EnginePlayer
from teacher.stockfish import StockfishTeacher
from train.evaluate import estimate_elo, play_game
from train.progress import ProgressLogger
from train.selfplay import play_selfplay_game
from train.supervised import policy_loss


# --------------------------------------------------------------------------- #
# Parallel self-play workers (generate games from the current champion)
# --------------------------------------------------------------------------- #
_SP: dict = {}


def _sp_init(
    model_config: dict,
    config: Config,
    sp_device: str,
    sf_value_weight: float,
    resign_cfg: dict,
    opening_book_path: str,
    syzygy_path: str,
) -> None:
    # Pin each worker to one CPU thread so N workers don't each spawn N intra-op
    # threads and thrash the cores.
    os.environ["CHESSAI_INFER"] = "torch"
    for _thread_var in (
        "OPENBLAS_NUM_THREADS",
        "OMP_NUM_THREADS",
        "MKL_NUM_THREADS",
        "VECLIB_MAXIMUM_THREADS",
        "NUMEXPR_NUM_THREADS",
    ):
        os.environ[_thread_var] = "1"
    try:
        torch.set_num_threads(1)
    except Exception:
        pass
    config.device = sp_device
    _SP["model_config"] = model_config
    _SP["config"] = config
    _SP["device"] = sp_device
    _SP["version"] = None
    _SP["player"] = None
    _SP["sf_value_weight"] = sf_value_weight
    _SP["resign_cfg"] = resign_cfg
    _SP["tablebase"] = try_load_tablebase(syzygy_path)
    _SP["opening_book"] = try_load_opening_book(opening_book_path)
    _SP["teacher"] = (
        StockfishTeacher(config.stockfish_path, depth=8, multipv=1)
        if sf_value_weight > 0.0
        else None
    )


def _sp_play(task):
    try:
        return _sp_play_inner(task)
    except Exception:
        import traceback

        return {"__error__": traceback.format_exc()}


def _sp_play_inner(task):
    version, weights_path, sims, temperature_moves, seed = task
    # Reload weights only when the champion changes (a new promotion version).
    if _SP["version"] != version:
        model = build_model(ModelConfig(**_SP["model_config"]), device=_SP["device"])
        ckpt = torch.load(weights_path, map_location=_SP["device"], weights_only=False)
        model.load_state_dict(ckpt["state_dict"])
        model.eval()
        _SP["player"] = EnginePlayer(model, _SP["config"])
        _SP["version"] = version

    np.random.seed(seed % (2 ** 32))
    rng = random.Random(seed)
    samples, white_result = play_selfplay_game(
        _SP["player"],
        sims=sims,
        temperature_moves=temperature_moves,
        teacher=_SP["teacher"],
        sf_value_weight=_SP["sf_value_weight"],
        rng=rng,
        tablebase=_SP["tablebase"],
        **_SP["resign_cfg"],
    )
    packed = [(p.astype(np.uint8), pi, float(z)) for (p, pi, z) in samples]
    return packed, float(white_result)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _gate_promote(
    wins: int,
    draws: int,
    losses: int,
    threshold: float,
    min_games: int,
    require_significance: bool = True,
) -> Tuple[bool, str]:
    """Return (should_promote, reason)."""
    n = wins + draws + losses
    if n < min_games:
        return False, f"insufficient_games ({n} < {min_games})"
    score = (wins + 0.5 * draws) / n
    if score < threshold:
        return False, f"below_threshold ({score:.3f} < {threshold})"
    if require_significance and n > 0:
        # One-sided normal approx: H0 true score = 0.5 (even match).
        se = 0.5 / (n ** 0.5)
        z = (score - 0.5) / se
        if z < 1.645:  # ~95% one-sided
            return False, f"not_significant (z={z:.2f}, need >=1.645)"
    return True, "promoted"


def _sup_batch(dataset: StockfishDataset, n: int, device: str):
    """Sample ``n`` random ground-truth positions from the supervised corpus."""
    idxs = np.random.randint(0, len(dataset), size=n)
    planes, policies, values = [], [], []
    for i in idxs:
        p, pol, v = dataset[int(i)]
        planes.append(p)
        policies.append(pol)
        values.append(v)
    return (
        torch.stack(planes).to(device),
        torch.stack(policies).to(device),
        torch.stack(values).to(device),
    )


def _arena_game(
    white_player: EnginePlayer,
    black_player: EnginePlayer,
    opening: List[chess.Move],
    sims: int,
    temperature: float,
    temp_moves: int,
    max_moves: int = 240,
    tablebase=None,
) -> float:
    """Play one arena game from a fixed opening. Returns white-perspective result
    (1.0 white win, 0.0 draw, -1.0 black win)."""
    board = chess.Board()
    for mv in opening:
        if mv in board.legal_moves:
            board.push(mv)

    n = 0
    while not board.is_game_over(claim_draw=True) and board.fullmove_number < max_moves:
        if tablebase is not None:
            wr = tablebase_forced_white_result(board, tablebase)
            if wr is not None:
                return wr

        player = white_player if board.turn == chess.WHITE else black_player
        temp = temperature if n < temp_moves else 0.0
        move, _ = player.select_move(
            board, simulations=sims, temperature=temp, add_noise=temp > 0.0
        )
        board.push(move)
        n += 1

    outcome = board.outcome(claim_draw=True)
    if outcome is None or outcome.winner is None:
        return 0.0
    return 1.0 if outcome.winner == chess.WHITE else -1.0


def _arena(
    cand_player: EnginePlayer,
    champ_player: EnginePlayer,
    games: int,
    sims: int,
    rng: random.Random,
    opening_pool: Optional[List[List[chess.Move]]] = None,
    opening_min: int = 4,
    opening_max: int = 12,
    temperature: float = 0.0,
    temp_moves: int = 0,
    progress: Optional[ProgressLogger] = None,
    iter_idx: int = 0,
    tablebase=None,
) -> Tuple[float, int, int, int]:
    """Candidate-vs-champion match in *mirrored pairs*.

    Each pair shares an opening (from ``opening_pool`` when provided) and is
    played twice with colors swapped, so opening/color imbalance cancels out.
    Returns (candidate_score, W, D, L).
    """
    pairs = max(1, games // 2)
    total = 0.0
    wins = draws = losses = 0

    def tally(cand_score: float) -> None:
        nonlocal total, wins, draws, losses
        total += cand_score
        if cand_score == 1.0:
            wins += 1
        elif cand_score == 0.5:
            draws += 1
        else:
            losses += 1

    for _ in range(pairs):
        if opening_pool:
            opening = opening_pool[rng.randrange(len(opening_pool))]
        else:
            board = chess.Board()
            opening = []
            k = rng.randint(opening_min, opening_max)
            for _ in range(k):
                if board.is_game_over():
                    break
                mv = rng.choice(list(board.legal_moves))
                opening.append(mv)
                board.push(mv)

        # Game A: candidate as White.
        wr = _arena_game(cand_player, champ_player, opening, sims, temperature, temp_moves, tablebase=tablebase)
        cand_a = (wr + 1.0) / 2.0
        # Game B (mirror): candidate as Black.
        wr2 = _arena_game(champ_player, cand_player, opening, sims, temperature, temp_moves, tablebase=tablebase)
        cand_b = (1.0 - wr2) / 2.0

        tally(cand_a)
        tally(cand_b)
        if progress:
            progress.log({
                "event": "arena_game", "iter": iter_idx,
                "white_result_a": wr, "white_result_b": wr2,
                "cand_pair_score": round(cand_a + cand_b, 1),
            })

    return total / (pairs * 2), wins, draws, losses


def train_selfplay(
    config: Optional[Config] = None,
    iterations: int = 40,
    games_per_iter: int = 48,
    sims: int = 200,
    train_steps: int = 200,
    batch_size: int = 256,
    lr: float = 1e-4,
    buffer_capacity: int = 300_000,
    init_checkpoint: Optional[str] = "models/supervised.pt",
    out_name: str = "selfplay.pt",
    best_name: str = "best.pt",
    sf_value_weight: float = 0.0,
    temperature_moves: int = 25,
    workers: int = 1,
    selfplay_device: Optional[str] = None,
    sup_fraction: float = 0.5,
    resign: bool = True,
    resign_threshold: float = 0.95,
    resign_streak: int = 3,
    complete_fraction: float = 0.08,
    arena_every: int = 3,
    arena_games: int = 300,
    arena_sims: Optional[int] = None,
    arena_opening_pool: int = 50,
    arena_book_fraction: float = 0.7,
    arena_opening_min: int = 6,
    arena_opening_max: int = 24,
    arena_temperature: float = 0.0,
    arena_temp_moves: int = 0,
    gate_threshold: float = 0.55,
    gate_min_games: int = 300,
    gate_require_significance: bool = True,
    eval_every: int = 0,
    eval_games: int = 50,
    eval_skill: int = 5,
    eval_sims: Optional[int] = None,
    progress: Optional[ProgressLogger] = None,
    start_iter: int = 0,
) -> str:
    config = config or Config()
    config.ensure_dirs()
    progress = progress or ProgressLogger(
        os.path.join(config.logs_dir, "selfplay.jsonl"), append=start_iter > 0
    )
    device = config.device
    arena_sims = arena_sims or sims
    eval_sims = eval_sims or sims
    resign_cfg = {
        "resign": resign,
        "resign_threshold": resign_threshold,
        "resign_streak": resign_streak,
        "complete_fraction": complete_fraction,
    }

    # Champion (generates games, is the deployed net) and candidate (trained).
    if init_checkpoint and os.path.exists(init_checkpoint):
        champion, _ = load_checkpoint(init_checkpoint, device=device)
    else:
        champion = build_model(config.model, device=device)
    candidate = build_model(champion.config, device=device)
    candidate.load_state_dict(champion.state_dict())

    optimizer = torch.optim.Adam(candidate.parameters(), lr=lr, weight_decay=1e-4)
    buffer = ReplayBuffer(capacity=buffer_capacity)

    champ_player = EnginePlayer(champion, config)
    cand_player = EnginePlayer(candidate, config)

    # Supervised anchor corpus (mixed into every training batch).
    sup_dataset = None
    if sup_fraction > 0.0:
        try:
            ds = StockfishDataset(config.data_dir)
            if len(ds) > 0:
                sup_dataset = ds
        except Exception:
            sup_dataset = None

    parallel = workers and workers > 1
    sp_device = selfplay_device or ("cpu" if parallel else device)

    for _thread_var in (
        "OPENBLAS_NUM_THREADS",
        "OMP_NUM_THREADS",
        "MKL_NUM_THREADS",
        "VECLIB_MAXIMUM_THREADS",
        "NUMEXPR_NUM_THREADS",
        "CHESSAI_INFER",
    ):
        if _thread_var == "CHESSAI_INFER":
            os.environ[_thread_var] = "torch"
        else:
            os.environ[_thread_var] = "1"
    try:
        torch.set_num_threads(1)
    except Exception:
        pass

    teacher = None
    tablebase = try_load_tablebase(config.syzygy_path)
    opening_book = try_load_opening_book(config.opening_book_path)
    if sf_value_weight > 0.0 and not parallel:
        teacher = StockfishTeacher(config.stockfish_path, depth=8, multipv=1)

    out_path = os.path.join(config.models_dir, out_name)
    best_path = os.path.join(config.models_dir, best_name)
    weights_path = os.path.join(config.models_dir, "_sp_weights.pt")

    # Publish the champion's weights for the workers (version bumps on promotion).
    champ_version = 0
    save_checkpoint(weights_path, champion)

    pool = None
    if parallel:
        ctx = mp.get_context("spawn")
        pool = ctx.Pool(
            processes=workers,
            initializer=_sp_init,
            initargs=(
                vars(champion.config), config, sp_device, sf_value_weight, resign_cfg,
                config.opening_book_path, config.syzygy_path,
            ),
        )

    rng = random.Random(20240703)
    opening_pool = build_mixed_opening_pool(
        rng,
        size=arena_opening_pool,
        book=opening_book,
        book_fraction=arena_book_fraction,
        min_plies=arena_opening_min,
        max_plies=arena_opening_max,
        random_min_plies=4,
        random_max_plies=12,
    )

    progress.log(
        {
            "event": "start",
            "mode": "selfplay",
            "iterations": iterations,
            "start_iter": start_iter,
            "games_per_iter": games_per_iter,
            "sims": sims,
            "device": device,
            "workers": workers,
            "selfplay_device": sp_device,
            "lr": lr,
            "sup_fraction": sup_fraction if sup_dataset else 0.0,
            "sup_samples": len(sup_dataset) if sup_dataset else 0,
            "arena_every": arena_every,
            "arena_games": arena_games,
            "gate_threshold": gate_threshold,
            "gate_min_games": gate_min_games,
            "arena_opening_pool": arena_opening_pool,
            "arena_book_fraction": arena_book_fraction,
            "opening_book": bool(opening_book),
            "tablebase": bool(tablebase),
            "resign": resign,
        }
    )

    # Save the starting champion as the initial best.
    save_checkpoint(best_path, champion, meta={"iter": -1, "note": "init"})

    try:
        for it in range(start_iter, iterations):
            # ---- 1. Generate self-play games from the CHAMPION ----
            champion.eval()
            if parallel:
                tasks = [
                    (champ_version, weights_path, sims, temperature_moves, it * 100_003 + g)
                    for g in range(games_per_iter)
                ]
                done = 0
                for result in pool.imap_unordered(_sp_play, tasks):
                    if isinstance(result, dict) and "__error__" in result:
                        progress.log({"event": "worker_error", "iter": it, "traceback": result["__error__"]})
                        raise RuntimeError(f"Self-play worker failed:\n{result['__error__']}")
                    samples, white_result = result
                    buffer.add_game(samples)
                    done += 1
                    progress.log(
                        {
                            "event": "selfplay_game",
                            "iter": it,
                            "game": done,
                            "games_per_iter": games_per_iter,
                            "samples": len(samples),
                            "result": white_result,
                            "buffer": len(buffer),
                        }
                    )
            else:
                for g in range(games_per_iter):
                    samples, white_result = play_selfplay_game(
                        champ_player,
                        sims=sims,
                        temperature_moves=temperature_moves,
                        teacher=teacher,
                        sf_value_weight=sf_value_weight,
                        tablebase=tablebase,
                        **resign_cfg,
                    )
                    buffer.add_game(samples)
                    progress.log(
                        {
                            "event": "selfplay_game",
                            "iter": it,
                            "game": g + 1,
                            "games_per_iter": games_per_iter,
                            "samples": len(samples),
                            "result": white_result,
                            "buffer": len(buffer),
                        }
                    )

            # ---- 2. Train the CANDIDATE (self-play + supervised anchor) ----
            candidate.train()
            if len(buffer) >= batch_size:
                n_sup = int(round(batch_size * sup_fraction)) if sup_dataset else 0
                n_buf = batch_size - n_sup
                for step in range(train_steps):
                    bp, bpi, bv = buffer.sample_batch(n_buf)
                    if n_sup:
                        sp_, spi, sv = _sup_batch(sup_dataset, n_sup, device)
                        planes = torch.cat([bp.to(device), sp_], dim=0)
                        target_policy = torch.cat([bpi.to(device), spi], dim=0)
                        target_value = torch.cat([bv.to(device), sv], dim=0)
                    else:
                        planes = bp.to(device)
                        target_policy = bpi.to(device)
                        target_value = bv.to(device)

                    logits, value = candidate(planes)
                    p_loss = policy_loss(logits, target_policy)
                    v_loss = F.mse_loss(value, target_value)
                    loss = p_loss + v_loss

                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

                    if step % 25 == 0:
                        progress.log(
                            {
                                "event": "train_step",
                                "iter": it,
                                "step": step,
                                "policy_loss": round(p_loss.item(), 4),
                                "value_loss": round(v_loss.item(), 4),
                            }
                        )

            save_checkpoint(out_path, candidate, meta={"iter": it})

            # ---- 3. Arena gating: promote only if candidate beats champion ----
            if arena_every and (it + 1) % arena_every == 0 and len(buffer) >= batch_size:
                candidate.eval()
                champion.eval()
                score, w, d, l = _arena(
                    cand_player, champ_player, arena_games, arena_sims, rng,
                    opening_pool=opening_pool,
                    opening_min=arena_opening_min, opening_max=arena_opening_max,
                    temperature=arena_temperature, temp_moves=arena_temp_moves,
                    progress=progress, iter_idx=it, tablebase=tablebase,
                )
                promote, reason = _gate_promote(
                    w, d, l, gate_threshold, gate_min_games, gate_require_significance,
                )
                if promote:
                    champion.load_state_dict(candidate.state_dict())
                    champ_version += 1
                    save_checkpoint(weights_path, champion)  # refresh workers
                    save_checkpoint(best_path, champion, meta={"iter": it, "arena_score": score})
                    progress.log(
                        {
                            "event": "promote",
                            "iter": it,
                            "arena_score": round(score, 3),
                            "gate_reason": reason,
                            "wins": w, "draws": d, "losses": l,
                            "champ_version": champ_version,
                        }
                    )
                else:
                    # Reject: revert candidate to the champion so it can't drift off.
                    candidate.load_state_dict(champion.state_dict())
                    progress.log(
                        {
                            "event": "arena_reject",
                            "iter": it,
                            "arena_score": round(score, 3),
                            "gate_reason": reason,
                            "wins": w, "draws": d, "losses": l,
                        }
                    )

            # ---- 4. Optional absolute Elo check vs Stockfish (champion) ----
            if eval_every and (it + 1) % eval_every == 0:
                champion.eval()
                result = estimate_elo(
                    champ_player, config, games=eval_games,
                    sims=eval_sims, skill_level=eval_skill, progress=progress,
                )
                progress.log({"event": "champion_elo", "iter": it,
                              "estimated_elo": result["estimated_elo"]})

            progress.log({"event": "iter_done", "iter": it})
    finally:
        if teacher is not None:
            teacher.close()
        if opening_book is not None:
            opening_book.close()
        if tablebase is not None:
            tablebase.close()
        if pool is not None:
            pool.close()
            pool.join()

    progress.log({"event": "done", "mode": "selfplay", "checkpoint": best_path,
                  "champ_version": champ_version})
    return best_path
