"""AlphaZero-style refinement loop with safeguards against collapse.

Naive self-play from a good supervised net tends to *degrade* it: the net
overfits its own noisy, exploration-heavy games and forgets what Stockfish
taught it (catastrophic forgetting). This loop adds the guardrails that make
self-play actually help:

1. Champion/candidate split + arena gating -- a freshly trained candidate is
   only promoted to champion if it *beats* the current champion head-to-head by
   a margin. Otherwise it is reverted. The deployed net can therefore never get
   worse than where it started.
2. Supervised anchoring -- every training batch mixes a fraction of ground-truth
   Stockfish-labeled positions in with the self-play samples, so the net keeps
   its supervised knowledge instead of drifting away from it.
3. A conservative learning rate and self-play games generated by the *champion*
   (not the possibly-degraded candidate), so training data stays high quality.
4. Optional Stockfish value blending into self-play value targets.

Self-play game generation is parallelized across worker processes (see the
``_sp_*`` helpers); the champion's weights are broadcast to the workers and only
reloaded when the champion is promoted.
"""
from __future__ import annotations

import multiprocessing as mp
import os
import random
from typing import List, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F

from data.dataset import ReplayBuffer, StockfishDataset
from engine.config import Config, ModelConfig
from engine.model import build_model, load_checkpoint, save_checkpoint
from engine.player import EnginePlayer
from teacher.stockfish import StockfishTeacher
from train.evaluate import estimate_elo, play_game
from train.progress import ProgressLogger
from train.selfplay import play_selfplay_game
from train.supervised import policy_loss


# --------------------------------------------------------------------------- #
# Parallel self-play workers (generate games from the current champion)
# --------------------------------------------------------------------------- #
_SP: dict = {}


def _sp_init(model_config: dict, config: Config, sp_device: str, sf_value_weight: float) -> None:
    # Pin each worker to one CPU thread so N workers don't each spawn N intra-op
    # threads and thrash the cores.
    try:
        torch.set_num_threads(1)
    except Exception:
        pass
    config.device = sp_device
    _SP["model_config"] = model_config
    _SP["config"] = config
    _SP["device"] = sp_device
    _SP["version"] = None
    _SP["player"] = None
    _SP["sf_value_weight"] = sf_value_weight
    _SP["teacher"] = (
        StockfishTeacher(config.stockfish_path, depth=8, multipv=1)
        if sf_value_weight > 0.0
        else None
    )


def _sp_play(task):
    version, weights_path, sims, temperature_moves, seed = task
    # Reload weights only when the champion changes (a new promotion version).
    if _SP["version"] != version:
        model = build_model(ModelConfig(**_SP["model_config"]), device=_SP["device"])
        ckpt = torch.load(weights_path, map_location=_SP["device"])
        model.load_state_dict(ckpt["state_dict"])
        model.eval()
        _SP["player"] = EnginePlayer(model, _SP["config"])
        _SP["version"] = version

    np.random.seed(seed % (2 ** 32))
    rng = random.Random(seed)
    samples = play_selfplay_game(
        _SP["player"],
        sims=sims,
        temperature_moves=temperature_moves,
        teacher=_SP["teacher"],
        sf_value_weight=_SP["sf_value_weight"],
        rng=rng,
    )
    return [(p.astype(np.uint8), pi, float(z)) for (p, pi, z) in samples]


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _sup_batch(dataset: StockfishDataset, n: int, device: str):
    """Sample ``n`` random ground-truth positions from the supervised corpus."""
    idxs = np.random.randint(0, len(dataset), size=n)
    planes, policies, values = [], [], []
    for i in idxs:
        p, pol, v = dataset[int(i)]
        planes.append(p)
        policies.append(pol)
        values.append(v)
    return (
        torch.stack(planes).to(device),
        torch.stack(policies).to(device),
        torch.stack(values).to(device),
    )


def _arena(cand_player: EnginePlayer, champ_player: EnginePlayer, games: int,
           sims: int, rng: random.Random) -> Tuple[float, int, int, int]:
    """Play ``games`` candidate-vs-champion. Returns (candidate_score, W, D, L)."""
    def champ_move(board):
        move, _ = champ_player.select_move(board, simulations=sims, temperature=0.0)
        return move

    total = 0.0
    wins = draws = losses = 0
    for g in range(games):
        cand_white = g % 2 == 0
        r = play_game(cand_player, champ_move, cand_white, sims, rng=rng)
        total += r
        if r == 1.0:
            wins += 1
        elif r == 0.5:
            draws += 1
        else:
            losses += 1
    return total / games, wins, draws, losses


def train_selfplay(
    config: Optional[Config] = None,
    iterations: int = 40,
    games_per_iter: int = 48,
    sims: int = 200,
    train_steps: int = 200,
    batch_size: int = 256,
    lr: float = 1e-4,
    buffer_capacity: int = 300_000,
    init_checkpoint: Optional[str] = "models/supervised.pt",
    out_name: str = "selfplay.pt",
    sf_value_weight: float = 0.0,
    temperature_moves: int = 20,
    workers: int = 1,
    selfplay_device: Optional[str] = None,
    sup_fraction: float = 0.5,
    arena_every: int = 3,
    arena_games: int = 16,
    arena_sims: Optional[int] = None,
    gate_threshold: float = 0.55,
    eval_every: int = 0,
    eval_games: int = 20,
    eval_skill: int = 5,
    progress: Optional[ProgressLogger] = None,
) -> str:
    config = config or Config()
    config.ensure_dirs()
    progress = progress or ProgressLogger(os.path.join(config.logs_dir, "selfplay.jsonl"))
    device = config.device
    arena_sims = arena_sims or max(100, sims // 2)

    # Champion (generates games, is the deployed net) and candidate (trained).
    if init_checkpoint and os.path.exists(init_checkpoint):
        champion, _ = load_checkpoint(init_checkpoint, device=device)
    else:
        champion = build_model(config.model, device=device)
    candidate = build_model(champion.config, device=device)
    candidate.load_state_dict(champion.state_dict())

    optimizer = torch.optim.Adam(candidate.parameters(), lr=lr, weight_decay=1e-4)
    buffer = ReplayBuffer(capacity=buffer_capacity)

    champ_player = EnginePlayer(champion, config)
    cand_player = EnginePlayer(candidate, config)

    # Supervised anchor corpus (mixed into every training batch).
    sup_dataset = None
    if sup_fraction > 0.0:
        try:
            ds = StockfishDataset(config.data_dir)
            if len(ds) > 0:
                sup_dataset = ds
        except Exception:
            sup_dataset = None

    parallel = workers and workers > 1
    sp_device = selfplay_device or ("cpu" if parallel else device)

    teacher = None
    if sf_value_weight > 0.0 and not parallel:
        teacher = StockfishTeacher(config.stockfish_path, depth=8, multipv=1)

    out_path = os.path.join(config.models_dir, out_name)
    best_path = os.path.join(config.models_dir, "best.pt")
    weights_path = os.path.join(config.models_dir, "_sp_weights.pt")

    # Publish the champion's weights for the workers (version bumps on promotion).
    champ_version = 0
    save_checkpoint(weights_path, champion)

    pool = None
    if parallel:
        ctx = mp.get_context("spawn")
        pool = ctx.Pool(
            processes=workers,
            initializer=_sp_init,
            initargs=(vars(champion.config), config, sp_device, sf_value_weight),
        )

    rng = random.Random(20240703)

    progress.log(
        {
            "event": "start",
            "mode": "selfplay",
            "iterations": iterations,
            "games_per_iter": games_per_iter,
            "sims": sims,
            "device": device,
            "workers": workers,
            "selfplay_device": sp_device,
            "lr": lr,
            "sup_fraction": sup_fraction if sup_dataset else 0.0,
            "sup_samples": len(sup_dataset) if sup_dataset else 0,
            "arena_every": arena_every,
            "arena_games": arena_games,
            "gate_threshold": gate_threshold,
        }
    )

    # Save the starting champion as the initial best.
    save_checkpoint(best_path, champion, meta={"iter": -1, "note": "init"})

    try:
        for it in range(iterations):
            # ---- 1. Generate self-play games from the CHAMPION ----
            champion.eval()
            if parallel:
                tasks = [
                    (champ_version, weights_path, sims, temperature_moves, it * 100_003 + g)
                    for g in range(games_per_iter)
                ]
                done = 0
                for samples in pool.imap_unordered(_sp_play, tasks):
                    buffer.add_game(samples)
                    done += 1
                    progress.log(
                        {
                            "event": "selfplay_game",
                            "iter": it,
                            "game": done,
                            "games_per_iter": games_per_iter,
                            "samples": len(samples),
                            "buffer": len(buffer),
                        }
                    )
            else:
                for g in range(games_per_iter):
                    samples = play_selfplay_game(
                        champ_player,
                        sims=sims,
                        temperature_moves=temperature_moves,
                        teacher=teacher,
                        sf_value_weight=sf_value_weight,
                    )
                    buffer.add_game(samples)
                    progress.log(
                        {
                            "event": "selfplay_game",
                            "iter": it,
                            "game": g + 1,
                            "games_per_iter": games_per_iter,
                            "samples": len(samples),
                            "buffer": len(buffer),
                        }
                    )

            # ---- 2. Train the CANDIDATE (self-play + supervised anchor) ----
            candidate.train()
            if len(buffer) >= batch_size:
                n_sup = int(round(batch_size * sup_fraction)) if sup_dataset else 0
                n_buf = batch_size - n_sup
                for step in range(train_steps):
                    bp, bpi, bv = buffer.sample_batch(n_buf)
                    if n_sup:
                        sp_, spi, sv = _sup_batch(sup_dataset, n_sup, device)
                        planes = torch.cat([bp.to(device), sp_], dim=0)
                        target_policy = torch.cat([bpi.to(device), spi], dim=0)
                        target_value = torch.cat([bv.to(device), sv], dim=0)
                    else:
                        planes = bp.to(device)
                        target_policy = bpi.to(device)
                        target_value = bv.to(device)

                    logits, value = candidate(planes)
                    p_loss = policy_loss(logits, target_policy)
                    v_loss = F.mse_loss(value, target_value)
                    loss = p_loss + v_loss

                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

                    if step % 25 == 0:
                        progress.log(
                            {
                                "event": "train_step",
                                "iter": it,
                                "step": step,
                                "policy_loss": round(p_loss.item(), 4),
                                "value_loss": round(v_loss.item(), 4),
                            }
                        )

            save_checkpoint(out_path, candidate, meta={"iter": it})

            # ---- 3. Arena gating: promote only if candidate beats champion ----
            if arena_every and (it + 1) % arena_every == 0 and len(buffer) >= batch_size:
                candidate.eval()
                champion.eval()
                score, w, d, l = _arena(cand_player, champ_player, arena_games, arena_sims, rng)
                if score >= gate_threshold:
                    champion.load_state_dict(candidate.state_dict())
                    champ_version += 1
                    save_checkpoint(weights_path, champion)  # refresh workers
                    save_checkpoint(best_path, champion, meta={"iter": it, "arena_score": score})
                    progress.log(
                        {
                            "event": "promote",
                            "iter": it,
                            "arena_score": round(score, 3),
                            "wins": w, "draws": d, "losses": l,
                            "champ_version": champ_version,
                        }
                    )
                else:
                    # Reject: revert candidate to the champion so it can't drift off.
                    candidate.load_state_dict(champion.state_dict())
                    progress.log(
                        {
                            "event": "arena_reject",
                            "iter": it,
                            "arena_score": round(score, 3),
                            "wins": w, "draws": d, "losses": l,
                        }
                    )

            # ---- 4. Optional absolute Elo check vs Stockfish (champion) ----
            if eval_every and (it + 1) % eval_every == 0:
                champion.eval()
                result = estimate_elo(
                    champ_player, config, games=eval_games,
                    sims=max(40, sims // 2), skill_level=eval_skill, progress=progress,
                )
                progress.log({"event": "champion_elo", "iter": it,
                              "estimated_elo": result["estimated_elo"]})
    finally:
        if teacher is not None:
            teacher.close()
        if pool is not None:
            pool.close()
            pool.join()

    progress.log({"event": "done", "mode": "selfplay", "checkpoint": best_path,
                  "champ_version": champ_version})
    return best_path
